version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"  # Frontend exposed on port 5000
  backend:
    build: ./backend
    ports:
      - "7000:7000"  # Backend exposed on port 7000
    environment:
      MONGO_URI: mongodb://database:27017/mern_devops_db
  database:
    image: mongo
    ports:
      - "27017:27017"  # MongoDB port
  sonar:
    image: sonarqube
    ports:
      - "9000:9000"  # SonarQube UI accessible at localhost:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar

